### ISSUE TITLE
Possible deadlock on slow VMs/devices

### ISSUE THREAD

**Issue by tcalmant** [ECF/Py4j-RemoteServicesProvider#2]
Hi,

An issue appeared during the development of the iPOPO project, [described in issue #100](https://github.com/tcalmant/ipopo/issues/100).
Long story short: after using the Py4J provider, when trying to shut down the framework, the process was blocked, waiting for a Thread Pool Executor to stop.
This blocks due to a thread ``join()`` call without timeout, inside the ``concurrent.future`` Python API.

This means that a method executed inside that thread pool is blocked, either by a lock or by a blocking method that doesn't time out.
The calls that use the executor are related to the following classes:
* ``PythonService`` (called in [iPOPO Py4J provider, around line 160](https://github.com/tcalmant/ipopo/blob/cdf267a7ed2b46cf88bd0585d19badaa07440174/pelix/rsa/providers/distribution/py4j.py#L144-L160))
* ``JavaServiceProxy`` (called in [iPOPO Py4J provider, around line 190](https://github.com/tcalmant/ipopo/blob/cdf267a7ed2b46cf88bd0585d19badaa07440174/pelix/rsa/providers/distribution/py4j.py#L186-L202))

The Protobuf versions could also have the problem, but they weren't tested when the issue occurred.
I have read the code of this methods a bit, but haven't found any issue yet.

Note that this problem doesn't happen all the time: it doesn't appear on my computer, but it was blocking most of Travis-CI builds for iPOPO.
The current workaround in iPOPO is to shutdown the thread pool executor without joining its threads.
This works, but it only hides the problem.

**Comment by scottslewis** [comment]
Turns out that it was a problem with graceful shutdown of the threads in the py4j distribution provider.   This does not seem to be a problem in the osgiservicebridge.  Closing this issue.
